version: "3.9"
services:
  webapp:
    build: ./webapp
    ports:
      - '8080:8080'
    volumes:
      - ./webapp:/app

  websocket_server:
    build: ./websocket_server
    ports:
      - '8765:8765'
    volumes:
      - ./websocket_server:/app

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes:
    #   - cache:/data
